# Generated by Django 5.2.16 on 2026-07-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('specialization', models.CharField(choices=[('cyber', 'Cybersécurité'), ('cloud', 'Cloud Computing'), ('ai', 'Intelligence Artificielle'), ('devsecops', 'DevSecOps'), ('data', 'Data & Analytics'), ('grc', 'Gouvernance IT & Risk'), ('forensics', 'Digital Forensics'), ('soc', 'SOC & Threat Intelligence'), ('archi', 'Architecture Cloud'), ('dev', 'Développement logiciel'), ('pm', 'Gestion de projets'), ('entrep', 'Entrepreneuriat tech'), ('other', 'Autre')], max_length=20, verbose_name='Spécialité')),
                ('level', models.CharField(choices=[('student', 'Étudiant'), ('junior', 'Junior (< 3 ans)'), ('mid', 'Confirmé (3-7 ans)'), ('senior', 'Senior (7+ ans)'), ('expert', 'Expert (15+ ans)')], max_length=20, verbose_name='Niveau')),
                ('country_of_origin', models.CharField(max_length=50, verbose_name="Pays d'origine")),
                ('city', models.CharField(max_length=50, verbose_name='Ville en Allemagne')),
                ('wants_mentor', models.BooleanField(default=False, verbose_name='Intéressé par le mentorat')),
                ('wants_newsletter', models.BooleanField(default=True, verbose_name='Newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pré-inscription',
                'verbose_name_plural': 'Pré-inscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
